#!/usr/bin/env bash

# The bottleneck is RAM, 8 GiB is not enough for 12 procs.
# If you want to adjust this, be sure to 'swapoff -a' before if you ever want
# to recover, be prepared to Alt+SysReq+B anyway.
MAXJOBS=8
MAXLOAD=12
OPTS="-DCMAKE_BUILD_TYPE=Debug -GNinja"

set -euo pipefail
cd "$(dirname "$0")"

./run-docker sh -c "mkdir -p build && cd build && cmake ${OPTS} .."
./run-docker sh -c "cd build && ninja -j ${MAXJOBS} -l ${MAXLOAD} $*"
