#!/usr/bin/env sh

userdir="$(getent passwd "$(whoami)" | cut -d: -f6)"

if [ -z "$MORROWIND_DIR" ]; then
    echo 'MORROWIND_DIR must point to the dir where Morrowind.exe is.'
    exit 1
fi

mkdir -p "$userdir/.config/openmw"
mkdir -p "$userdir/.local/share/openmw"

sudo docker run --rm -it \
    "-u$(id -u):$(id -g)" \
    --privileged \
    -v "$(pwd)/openmw:/app" \
    -v "/etc/passwd:/etc/passwd:ro" \
    -v "/etc/group:/etc/group:ro" \
    -v "$MORROWIND_DIR:/morrowind:ro" \
    -v "$userdir/.config/openmw:$userdir/.config/openmw" \
    -v "$userdir/.cache:$userdir/.cache" \
    -v "$userdir/.local/share/openmw:$userdir/.local/share/openmw" \
    -v "$XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR" \
    -v="/tmp/.X11-unix:/tmp/.X11-unix" \
    -e "XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR" \
    -e "DISPLAY=:0" \
    openmw "$@"
